# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flatpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_category', models.IntegerField(choices=[(1, 'Association'), (2, 'Activities'), (0, '(Top level)')])),
                ('menu_index', models.IntegerField(default=0)),
                ('flatpage_type', models.IntegerField(choices=[(0, 'Page'), (1, 'Direct Link')])),
                ('published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LocalFlatpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[(b'fi', 'Finnish'), (b'en', 'English')], max_length=5)),
                ('url', models.CharField(db_index=True, max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('menu_title', models.CharField(help_text='Shorter title that fits in menu elements', max_length=40)),
                ('content', models.TextField(help_text='Body text for pages, URL for direct links')),
                ('content_markup', models.CharField(choices=[(b'textile', b'Textile'), (b'none', b'None (no processing)'), (b'linebreaks', b'Linebreaks')], default=(b'textile', b'Textile'), max_length=20)),
                ('flatpage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flatpages.Flatpage')),
            ],
            options={
                'ordering': ('language', 'flatpage__menu_index', 'title'),
            },
        ),
        migrations.AlterUniqueTogether(
            name='localflatpage',
            unique_together=set([('url', 'language'), ('flatpage', 'language')]),
        ),
    ]
