# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0003_auto_20160221_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flatpage',
            options={'verbose_name': 'Flatpage', 'verbose_name_plural': 'Flatpages'},
        ),
        migrations.AlterModelOptions(
            name='localflatpage',
            options={'ordering': ('language', 'flatpage__menu_index', 'title'), 'verbose_name': 'Local Flatpage', 'verbose_name_plural': 'Local Flatpages'},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ('name',), 'verbose_name': 'Sponsor', 'verbose_name_plural': 'Sponsors'},
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='flatpage_type',
            field=models.IntegerField(choices=[(0, 'Page'), (1, 'Direct Link'), (2, 'Page with menu separator')], default=0, verbose_name='Flatpage type'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='menu_category',
            field=models.IntegerField(choices=[(1, b'Association'), (2, b'Activities'), (0, b'(Top level)')], default=0, verbose_name='Menu category'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='menu_index',
            field=models.IntegerField(default=0, help_text='Menus are sorted ascending by this value. The first menu item in a category is the category link itself. <strong>Note:</strong> The first menu item in the top level category should be the front page.', verbose_name='Menu index'),
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='published',
            field=models.BooleanField(default=False, help_text='Published pages show up on the menu. Unpublished pages can be reached over direct link.', verbose_name='Published'),
        ),
        migrations.AlterField(
            model_name='localflatpage',
            name='content',
            field=models.TextField(help_text='Body text for pages, URL for direct links', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='localflatpage',
            name='content_markup',
            field=models.CharField(choices=[(b'textile', b'Textile'), (b'none', b'None (no processing)'), (b'linebreaks', b'Linebreaks')], default=b'textile', max_length=20, verbose_name='Content markup'),
        ),
        migrations.AlterField(
            model_name='localflatpage',
            name='language',
            field=models.CharField(choices=[(b'fi', 'Finnish'), (b'en', 'English')], max_length=5, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='localflatpage',
            name='menu_title',
            field=models.CharField(blank=True, help_text='Shorter title that fits in menu elements', max_length=40, verbose_name='Menu Title'),
        ),
        migrations.AlterField(
            model_name='localflatpage',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='localflatpage',
            name='url',
            field=models.CharField(blank=True, db_index=True, help_text='The page is accessible on this path. Even external links have one.', max_length=100, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='titletext',
            field=models.CharField(blank=True, max_length=255, verbose_name='Title text'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
    ]
