# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0004_auto_20160221_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, upload_to='content_images/', verbose_name='Image')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'content image',
                'verbose_name_plural': 'content images',
            },
        ),
        migrations.AlterField(
            model_name='flatpage',
            name='flatpage_type',
            field=models.IntegerField(choices=[(0, 'Page'), (2, 'Page with menu separator'), (1, 'Direct Link'), (3, 'Direct Link with menu separator')], default=0, verbose_name='Flatpage type'),
        ),
    ]
