# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-26 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0005_auto_20160222_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('size', models.IntegerField(editable=False, verbose_name='Size')),
                ('uploaded_file', models.FileField(upload_to='download/', verbose_name='File')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'download',
                'verbose_name_plural': 'downloads',
            },
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name'),
        ),
    ]
