# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('officers', models.TextField()),
            ],
            options={
                'ordering': ('year',),
                'get_latest_by': 'year',
            },
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face', models.ImageField(upload_to='board_faces/%Y/')),
                ('role', models.IntegerField(choices=[(0, 'Chairman'), (1, 'Treasurer'), (2, 'Secretary'), (3, 'Vice chairman'), (4, 'Board Member'), (5, 'Study affairs'), (6, 'Communications'), (7, 'Corporate affairs'), (8, 'RV affairs'), (9, 'Freshman affairs'), (20, 'First deputy board member'), (21, 'Second deputy board member'), (22, 'Third deputy board member'), (23, 'Fourth deputy board member')])),
                ('contact', models.CharField(default='firstname.lastname(at)cs.helsinki.fi', max_length=100)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
            options={
                'ordering': ('role',),
            },
        ),
    ]
