# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-21 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'get_latest_by': 'year', 'ordering': ('year',), 'verbose_name': 'Board', 'verbose_name_plural': 'Boards'},
        ),
        migrations.AlterModelOptions(
            name='boardmember',
            options={'ordering': ('role',), 'verbose_name': 'Board Member', 'verbose_name_plural': 'Board Members'},
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='contact',
            field=models.CharField(default='firstname.lastname(at)cs.helsinki.fi', max_length=100, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='face',
            field=models.ImageField(upload_to='board_faces/%Y/', verbose_name='Mugshot'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='role',
            field=models.IntegerField(choices=[(0, 'Chairman'), (1, 'Treasurer'), (2, 'Secretary'), (3, 'Vice chairman'), (4, 'Board Member'), (5, 'Study affairs'), (6, 'Communications'), (7, 'Corporate affairs'), (8, 'RV affairs'), (9, 'Freshman affairs'), (20, 'First deputy board member'), (21, 'Second deputy board member'), (22, 'Third deputy board member'), (23, 'Fourth deputy board member')], verbose_name='Role'),
        ),
    ]
