# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-20 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TekisMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('screen_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('residence', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('hyy_member', models.BooleanField()),
                ('membership', models.CharField(choices=[(None, 'Nothing'), ('ei-jasen', 'Non-member'), ('erotettu', 'Membership revoked'), ('ulkojasen', 'External member'), ('jasen', 'Member'), ('kannatusjasen', 'Sponsor member'), ('kunniajasen', 'Honor member')], max_length=20)),
                ('role', models.CharField(choices=[(None, 'Nothing'), ('jasenvirkailija', 'Member officer'), ('kayttaja', 'Member'), ('virkailija', 'Officer'), ('yllapitaja', 'Administrator'), ('tenttiarkistovirkailija', 'Exam archive officer')], max_length=40)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('hashed_password', models.CharField(max_length=40)),
                ('salt', models.CharField(max_length=20)),
                ('tktl', models.BooleanField()),
                ('deleted', models.BooleanField()),
            ],
        ),
    ]
